//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int users_id { get; set; }
        public string users_name { get; set; }
        public int users_number { get; set; }
        public string users_email { get; set; }
        public string users_password { get; set; }
        public System.DateTime users_dob { get; set; }
        public int users_country_id { get; set; }
        public short users_credits { get; set; }
        public string users_diseases { get; set; }
        public bool users_mobility { get; set; }
    }
}
